name: Build packages

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.spec'
      - '.copr/**'
      - '.github/**'

jobs:
  main:
    if: |
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[build-all]') ||
      contains(github.event.head_commit.message, '[build-go]') ||
      contains(github.event.head_commit.message, '[build-rust]') ||
      contains(github.event.head_commit.message, '[build-python]') ||
      contains(github.event.head_commit.message, '[build-gcc]') ||
      contains(github.event.head_commit.message, '[build-themes]') ||
      contains(github.event.head_commit.message, '[build-prebuilt]') ||
      contains(github.event.head_commit.message, '[build-wayland]')
    runs-on: ubuntu-latest
    container:
      image: 'registry.fedoraproject.org/fedora-minimal:latest'

    steps:
      - name: Prepare
        run: |
          microdnf -y install --nodocs --setopt=install_weak_deps=0 \
            copr-cli parallel tar gzip git

      - name: Copr config
        env:
          COPR_CONF: ${{ secrets.COPR_CONFIG }}
        run: |
          mkdir -p ~/.config
          echo "$COPR_CONF" > ~/.config/copr

      - uses: actions/checkout@v4

      # Build wayland components first (dependency for scroll)
      - name: Build wayland components
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-wayland]') || contains(github.event.head_commit.message, '[build-gcc]')
        run: |
          # First build wayland
          wayland_build_id=$(copr-cli build-package mecattaf/duoRPM --nowait --name wayland | grep -o 'builds: [0-9]*' | cut -d' ' -f2)
          echo "WAYLAND_BUILD_ID=$wayland_build_id" >> $GITHUB_ENV
          
          # Then build wlroots after wayland
          wlroots_build_id=$(copr-cli build-package mecattaf/duoRPM --nowait --name wlroots --after-build-id "$WAYLAND_BUILD_ID" | grep -o 'builds: [0-9]*' | cut -d' ' -f2)
          echo "WLROOTS_BUILD_ID=$wlroots_build_id" >> $GITHUB_ENV

      # Prevent race conditions by starting with xcur2png
      - name: Build xcur2png first (dependency)
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-go]')
        run: |
          xcur2png_build_id=$(copr-cli build-package mecattaf/duoRPM --nowait --name xcur2png | grep -o 'builds: [0-9]*' | cut -d' ' -f2)
          echo "XCUR2PNG_BUILD_ID=$xcur2png_build_id" >> $GITHUB_ENV

      # Build cliphist second (dependency for nwg-clipman)
      - name: Build cliphist (dependency)
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-go]')
        run: |
          cliphist_build_id=$(copr-cli build-package mecattaf/duoRPM --nowait --name cliphist | grep -o 'builds: [0-9]*' | cut -d' ' -f2)
          echo "CLIPHIST_BUILD_ID=$cliphist_build_id" >> $GITHUB_ENV

      # Build GCC packages (lisgd, scroll)
      - name: Build GCC packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-gcc]')
        run: |
          copr-cli build-package mecattaf/duoRPM --nowait --name lisgd
          copr-cli build-package mecattaf/duoRPM --nowait --name scroll --after-build-id "$WLROOTS_BUILD_ID"
    
      # Build remaining Go packages (nwg-look) that depend on xcur2png
      - name: Build Go packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-go]')
        run: |
          # Build nwg-look after xcur2png
          copr-cli build-package mecattaf/duoRPM --nowait --name nwg-look --after-build-id "$XCUR2PNG_BUILD_ID"

      # Build Rust packages
      - name: Build Rust packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-rust]')
        run: |
          copr-cli build-package mecattaf/duoRPM --nowait --name wl-gammarelay-rs
          copr-cli build-package mecattaf/duoRPM --nowait --name matugen

      # Build Python packages with dependencies
      - name: Build Python packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-python]')
        run: |
          copr-cli build-package mecattaf/duoRPM --nowait --name python-autotiling
          copr-cli build-package mecattaf/duoRPM --nowait --name uwsm
          copr-cli build-package mecattaf/duoRPM --nowait --name nwg-clipman --after-build-id "$CLIPHIST_BUILD_ID"

      # Build theme packages
      - name: Build theme packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-themes]')
        run: |
          parallel copr-cli build-package mecattaf/duoRPM --nowait --name ::: \
            bibata-cursor-themes

      # Build prebuilt packages (atuin, eza, starship, iwmenu)
      - name: Build prebuilt packages
        if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build-all]') || contains(github.event.head_commit.message, '[build-prebuilt]')
        run: |
          # Build each prebuilt package independently since they tend to have specific issues
          copr-cli build-package mecattaf/duoRPM --nowait --name atuin
          copr-cli build-package mecattaf/duoRPM --nowait --name eza
          copr-cli build-package mecattaf/duoRPM --nowait --name starship
          copr-cli build-package mecattaf/duoRPM --nowait --name iwmenu

      # Check build status (fixed version)
      - name: Check build status
        if: always()
        run: |
          sleep 60  # Give COPR more time to register all builds
          copr-cli list-builds mecattaf/duoRPM
